// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package pkgutils

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../assets", "templates/template.bundle", "\"H4sIAAAAAAAA/+L/38zCyPS/hYGRh/F/EwMD3/9GEL8JxOdhYPi/CiTFVpZalJuYx8iXkpqUmZinm5yfV1KUn/O/NyAxOTsxPdVKobpaQc8vMTdVobaWKyy1qDgzPw8iCOWAxH0TM/NKEjPzUosgUgg+SNaxKDkjsyQ1uaS0CGoesghIhUtqcXJRZkEJ3GwkAZA8IAAA///dr/AYywAAAA==\"")
}
