image: registry.gitlab.768bit.com/vann/docker-images/vann-build-base-xgo:latest

variables:
  REPO_NAME: gitlab.768bit.com/github/vpkg

stages:
  - build
  - publish
  - clean

build docker-vpkg-reg:
  stage: build
  tags:
  - xgo-docker-build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.768bit.com
  - docker info
  script:
  - cp -rfv /cache/vcli-$CI_COMMIT_TAG/bin ./bin
  - $CI_PROJECT_DIR/scripts/build-docker-images-reg.sh


clean release:
  stage: clean
  tags:
  - docker-cleanup-cache
  only:
  - tags
  script:
  - echo "Cleaning Cache in /cache/vcli-$CI_COMMIT_TAG"
  - ls -la /cache/vcli-$CI_COMMIT_TAG
  - docker ps -f status=exited  | grep "\-cache-" | grep "\-project-${CI_PROJECT_ID}-" || true
  after_script:
  - rm -rf "/cache/vcli-$CI_COMMIT_TAG"
  when: always
